# Generated by Django 4.1.3 on 2022-11-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Components",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_name", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ValueTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ValueUnits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_unit", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Observations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monitored_id", models.IntegerField()),
                ("observation_name", models.CharField(max_length=500)),
                ("issued_at", models.DateTimeField()),
                ("component", models.ManyToManyField(to="app.components")),
            ],
        ),
        migrations.AddField(
            model_name="components",
            name="value_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.valuetypes"
            ),
        ),
        migrations.AddField(
            model_name="components",
            name="value_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.valueunits"
            ),
        ),
    ]
